### ISSUE TITLE
Reversing the order of images

### ISSUE THREAD

**Issue by nevitdilmen** [dreampowder/Osirix-ColorMRI#4]
(Sometimes) The plugin results in a series with a reversed order. (Reverse relative to source images)

This causes viewing difficulties, when trying to view images from same plane synchonusly. 

![screen shot 2018-01-19 at 18 04 28](https://user-images.githubusercontent.com/26278991/35192995-0e78a7aa-fead-11e7-8d40-b19decb7329d.png)
![screen shot 2018-01-19 at 18 04 35](https://user-images.githubusercontent.com/26278991/35192996-0ea37c8c-fead-11e7-8d8d-8ebe187d280a.png)

![screen shot 2018-01-10 at 16 10 19](https://user-images.githubusercontent.com/26278991/35193013-8274085c-fead-11e7-954c-68378be97a11.png)

**Comment by dreampowder** [comment]
I am not handling the order or images while composing the rgb image. Can you please send me the relevant image series and tell me which group does this behaviour? @nevitdilmen

**Comment by dreampowder** [comment]
Since it is hard to determine which parameter causes this event, and it is even harder to find more sample sets that results in reversed image orders, i've simply added "Reverse Order" checkbox into the  plugin ui. When user checks this button, image generation process will be reversed.
<img width="678" alt="screen shot 2018-05-23 at 15 39 02" src="https://user-images.githubusercontent.com/623593/40424926-9993c836-5e9f-11e8-81c8-07fdb1f239a3.png">
